import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NProgressHandler from '@/app/components/nprogress';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'IESB Saúde',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased`}>
      <NProgressHandler />
      <main>{children}</main>
      </body>
    </html>
  );
}
