import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NProgressHandler from '@/app/components/nprogress';
import { Suspense } from 'react';
import { ToastProvider } from "@/app/contexts/ToastContext";
import { ThemeProvider } from '@/app/contexts/ThemeContext'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'IESB Saúde',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased`}>
        <Suspense fallback={<div>Loading...</div>}>
          <NProgressHandler />
          <ThemeProvider>
            <ToastProvider>
              <main>{children}</main>
            </ToastProvider>
          </ThemeProvider>
          
        </Suspense>
      </body>
    </html>
  );
}
